print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
formacao: str = input(f"{nome} qual é a sua formação anterior?")
print(f"{formacao} parece-me um tema muito interessante!")
ano_de_formacao: str = input("Em que ano terminou o curso?")